print("Olá, Mundo!")

print("Este é um arquivo de exemplo em Python.")
print("Vamos aprender a programar em Python!")
print("Python é uma linguagem de programação poderosa e fácil de aprender.")
print("Divirta-se codificando!")
print("Obrigado por usar este exemplo de código!")
print("Até a próxima!")
print("Fim do programa.")
print("Este é o final do código.")
print("Tchau!") 
print("Até a próxima!")
print("Programa encerrado.")
print("Obrigado por executar este código.")
print("Adeus!")
print("Nos vemos em breve!")
print("Fique seguro e feliz codificação!")
print("Boa sorte em sua jornada de programação!")
print("Continue praticando e aprendendo!")
print("Você é incrível por estar aprendendo a programar!")
print("Nunca pare de explorar novas ideias!")